package com.adefaultdev.DummyVkBot.dsConnection;

import org.openqa.selenium.*;
import org.openqa.selenium.support.ui.*;
import java.time.Duration;
import java.util.List;

/**
 * Getting message from VK
 * Generates answer with DeepSeek and sends it back
 */
@SuppressWarnings("BusyWait")
public class DeepSeekClient {

    private final WebDriver driver;
    private final WebDriverWait wait;

    public DeepSeekClient(WebDriver driver) {
        this.driver = driver;
        this.wait = new WebDriverWait(driver, Duration.ofSeconds(30));
    }

    /**
     * Creating DeepSeek client
     * @param url - URL of DeepSeek site
     */
    public void setup(String url) {

        System.out.println("DeepSeek client is up. URL: " + url);

        try {

            JavascriptExecutor js = (JavascriptExecutor) driver; // This block used to bypass cloudflare
            js.executeScript("Object.defineProperty(navigator, 'webdriver', {get: () => undefined});");
            js.executeScript("window.navigator.chrome = {runtime: {}, etc: {}};");

            driver.get(url);

            Thread.sleep(5000);

            wait.until(ExpectedConditions.numberOfWindowsToBe(2));

            String originalWindow = driver.getWindowHandle();
            for (String windowHandle : driver.getWindowHandles()) {
                if (!windowHandle.equals(originalWindow)) {
                    driver.switchTo().window(windowHandle);
                    break;
                }
            }

            try {
                wait.until(ExpectedConditions.presenceOfElementLocated(
                        By.cssSelector("textarea[placeholder='Message DeepSeek']")
                ));
                System.out.println("[DeepSeek] Chat is loaded successfully.");
            } catch (TimeoutException e) {
                System.out.println("[DeepSeek ERROR] Unable to log in or accessing the chat");
                throw e;
            }

            driver.switchTo().window(originalWindow);

        } catch (Exception e) {
            System.out.println("[DeepSeek ERROR] " + e.getMessage());
            cleanupTabs();
        }
    }

    /**
     * Sends message to DeepSeek and getting a response
     * @param message - message from VK
     * @return - response from DeepSeek(null if error occur)
     */
    public String sendMessageAndGetResponse(String message) {
        try {

            String vkTab = driver.getWindowHandle();
            String deepSeekTab = driver.getWindowHandles()
                    .stream()
                    .filter(tab -> !tab.equals(vkTab))
                    .findFirst()
                    .orElseThrow(() -> new RuntimeException("No DeepSeek window found!"));

            driver.switchTo().window(deepSeekTab);

            List<WebElement> oldResponses = driver.findElements(
                    By.cssSelector("div.ds-markdown--block")
            );
            int prevResponseCount = oldResponses.size();

            WebElement chatInput = wait.until(
                    ExpectedConditions.elementToBeClickable(
                            By.cssSelector("textarea[placeholder='Message DeepSeek']")
                    )
            );
            chatInput.sendKeys(message);

            WebElement sendButton = wait.until(
                    ExpectedConditions.elementToBeClickable(
                            By.cssSelector("div[role='button'][aria-disabled='false']")
                    )
            );
            sendButton.click();



            String response = waitForResponse(prevResponseCount);

            driver.switchTo().window(vkTab);
            return response;

        } catch (Exception e) {
            System.out.println("[DeepSeek ERROR] " + e.getMessage());
            return null;
        }
    }

    private void cleanupTabs() {
        try {
            String mainWindow = driver.getWindowHandles().iterator().next();
            for (String handle : driver.getWindowHandles()) {
                if (!handle.equals(mainWindow)) {
                    driver.switchTo().window(handle).close();
                }
            }
            driver.switchTo().window(mainWindow);
        } catch (Exception e) {
            System.out.println("[DeepSeek ERROR] tabs cleanup  " + e.getMessage());
        }
    }


    /**
     * Awaiting answer from DeepSeek
     * @return - message generated by DeepSeek (null if error occur or timeout)
     */
    private String waitForResponse(int prevResponseCount) {
        final int MAX_WAIT_SEC = 60;
        final int POLL_INTERVAL_MS = 1000;
        final int STABLE_CHECKS_REQUIRED = 3;

        long startTime = System.currentTimeMillis();
        int stableChecks = 0;
        String lastText = "";

        try {
            while (System.currentTimeMillis() - startTime < MAX_WAIT_SEC * 1000) {
                List<WebElement> allResponses = driver.findElements(
                        By.cssSelector("div.ds-markdown--block")
                );

                if (allResponses.size() > prevResponseCount) {
                    WebElement newResponse = allResponses.get(allResponses.size() - 1);
                    String currentText = newResponse.getText()
                            .replaceAll("^\"|\"$", "")
                            .trim();

                    if (!currentText.equals(lastText)) {
                        lastText = currentText;
                        stableChecks = 0;
                    }

                    else if (!currentText.isEmpty()) {
                        stableChecks++;
                    }

                    if (stableChecks >= STABLE_CHECKS_REQUIRED) {
                        return currentText;
                    }
                }

                Thread.sleep(POLL_INTERVAL_MS);
            }
        } catch (Exception e) {
            System.out.println("[DeepSeek ERROR] while waiting for response: " + e.getMessage());
        }

        return null;
    }

}